import {getSupabaseClient} from './supabase.js';
const S={client:null,user:null,profile:null,events:[],clients:[],requests:[],templates:[],members:[],rsvps:[],checkins:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.addEventListener('DOMContentLoaded',init);
async function init(){S.client=await getSupabaseClient();$('#login-form').addEventListener('submit',login);$('[data-magic]').onclick=magic;$('[data-logout]').onclick=logout;$('[data-refresh]').onclick=load;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('[data-new-client]').forEach(b=>b.onclick=()=>openDialog('client-dialog'));$$('[data-new-event]').forEach(b=>b.onclick=openEvent);$$('[data-quick-event]').forEach(b=>b.onclick=openEvent);$$('[data-new-member]').forEach(b=>b.onclick=openMember);$('[data-new-template]').onclick=()=>openDialog('template-dialog');$('[data-open-requests]').onclick=()=>switchView('solicitudes');$('[data-go-events]').onclick=()=>switchView('eventos');$$('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#client-form').addEventListener('submit',saveClient);$('#event-form').addEventListener('submit',saveEvent);$('#member-form').addEventListener('submit',saveMember);$('#template-form').addEventListener('submit',saveTemplate);$('[data-event-search]').oninput=renderEvents;$('[data-event-status]').onchange=renderEvents;$('[data-client-search]').oninput=renderClients;$('[data-request-status]').onchange=renderRequests;$('[data-menu]').onclick=()=>document.body.classList.toggle('sidebar-open');const {data}=await S.client.auth.getSession();if(data.session)open(data.session.user)}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),st=$('#login-status');st.textContent='Verificando…';const {data,error}=await S.client.auth.signInWithPassword({email:String(f.get('email')).trim(),password:String(f.get('password'))});if(error)return st.textContent=error.message;open(data.user)}
async function magic(){const email=$('#login-form [name=email]').value.trim();if(!email)return $('#login-status').textContent='Escribe tu correo.';const {error}=await S.client.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+'/admin'}});$('#login-status').textContent=error?error.message:'Revisa tu correo para entrar.'}
async function open(user){S.user=user;const {data:p}=await S.client.from('profiles').select('*').eq('id',user.id).maybeSingle();S.profile=p||{global_role:'client'};$('[data-login]').hidden=true;$('[data-app]').hidden=false;$('[data-user-email]').textContent=user.email;$('[data-role]').textContent=S.profile.global_role==='owner'?'Propietario LN Studio':S.profile.global_role==='staff'?'Equipo LN Studio':'Cliente';document.body.classList.toggle('not-owner',!['owner','staff'].includes(S.profile.global_role));await load()}
async function load(){const calls=await Promise.all([S.client.from('events').select('*').order('created_at',{ascending:false}),S.client.from('clients').select('*').order('business_name'),S.client.from('quote_requests').select('*').order('created_at',{ascending:false}),S.client.from('templates').select('*').order('name'),S.client.from('event_members').select('*').order('created_at',{ascending:false}),S.client.from('rsvp_responses').select('event_id,attendance,party_size'),S.client.from('checkins').select('event_id,decision,entries')]);const [e,c,q,t,m,r,k]=calls;if(e.error)return alert(e.error.message);S.events=e.data||[];S.clients=c.data||[];S.requests=q.error?[]:q.data||[];S.templates=t.error?defaultTemplates():t.data||[];S.members=m.error?[]:m.data||[];S.rsvps=r.data||[];S.checkins=k.data||[];renderAll()}
function defaultTemplates(){return[{template_key:'biker-rebel-neon',name:'Rebel Neon',category:'biker',description:'Biker neón azul y rosa.'},{template_key:'aniversario-fantasmas',name:'Fantasmas Oficial',category:'aniversario',description:'Diseño privado oficial.'},{template_key:'boda-eternite',name:'Éternité',category:'boda',description:'Boda editorial.'},{template_key:'xv-eclat',name:'Éclat',category:'xv',description:'XV años premium.'}]}
function renderAll(){renderMetrics();renderEvents();renderClients();renderRequests();renderTemplates();renderMembers();populateSelects();$('[data-home-events]').innerHTML=eventCards(S.events.slice(0,3));}
function renderMetrics(){set('[data-metric-events]',S.events.filter(x=>!['archived','finished'].includes(x.status)).length);set('[data-metric-clients]',S.clients.length);set('[data-metric-requests]',S.requests.filter(x=>x.status==='new').length);set('[data-request-badge]',S.requests.filter(x=>x.status==='new').length);set('[data-metric-checkins]',S.checkins.filter(x=>x.decision==='approved').reduce((a,x)=>a+Number(x.entries||0),0)}
function renderEvents(){const q=($('[data-event-search]')?.value||'').toLowerCase(),status=$('[data-event-status]')?.value||'all',cm=new Map(S.clients.map(x=>[x.id,x]));const rows=S.events.filter(e=>(status==='all'||e.status===status)&&(!q||`${e.name} ${cm.get(e.client_id)?.business_name||''}`.toLowerCase().includes(q)));$('[data-events]').innerHTML=eventCards(rows);$('[data-events-empty]').hidden=rows.length>0}
function eventCards(rows){const cm=new Map(S.clients.map(x=>[x.id,x]));return rows.map(e=>{const conf=S.rsvps.filter(x=>x.event_id===e.id&&x.attendance==='confirmed').reduce((a,x)=>a+Number(x.party_size||0),0),check=S.checkins.filter(x=>x.event_id===e.id&&x.decision==='approved').reduce((a,x)=>a+Number(x.entries||0),0);return `<article class="event-card"><div class="event-card-top"><span class="status-pill status-${esc(e.status)}">${statusLabel(e.status)}</span><button class="dots" data-event-menu="${e.id}">•••</button></div><p class="admin-eyebrow">${esc(cm.get(e.client_id)?.business_name||'Sin cliente')}</p><h2>${esc(e.name)}</h2><p>${formatDate(e.event_date)}</p><div class="event-card-stats"><span><b>${conf}</b> confirmados</span><span><b>${check}</b> accesos</span></div><div class="event-card-actions"><a href="evento-admin.html?id=${e.id}">Administrar</a><a href="evento.html?token=${e.private_token}" target="_blank">Invitación</a><a href="scanner.html?event=${e.id}">Escáner</a></div></article>`}).join('')}
function renderClients(){const q=($('[data-client-search]').value||'').toLowerCase(),rows=S.clients.filter(c=>!q||`${c.business_name} ${c.contact_name||''} ${c.email||''}`.toLowerCase().includes(q));$('[data-clients]').innerHTML=rows.map(c=>`<article class="data-card"><span class="status-pill status-${c.status}">${esc(c.status)}</span><h3>${esc(c.business_name)}</h3><p>${esc(c.contact_name||'Sin contacto')}</p><dl><div><dt>Correo</dt><dd>${esc(c.email||'—')}</dd></div><div><dt>WhatsApp</dt><dd>${esc(c.phone||'—')}</dd></div><div><dt>Eventos</dt><dd>${S.events.filter(e=>e.client_id===c.id).length}</dd></div></dl><button data-client-event="${c.id}">Crear evento</button></article>`).join('');$('[data-clients-empty]').hidden=rows.length>0;$$('[data-client-event]').forEach(b=>b.onclick=()=>openEvent(b.dataset.clientEvent))}
function renderRequests(){const st=$('[data-request-status]').value,rows=S.requests.filter(r=>st==='all'||r.status===st);$('[data-requests]').innerHTML=rows.map(r=>`<article class="request-card"><div><span class="status-pill status-${r.status}">${requestStatus(r.status)}</span><h3>${esc(r.name)}</h3><p>${esc(r.event_type)} · ${esc(r.event_date||'Fecha por definir')} · ${Number(r.guest_count||0)} invitados</p><small>${formatDate(r.created_at)}</small></div><div><strong>${esc(r.phone||r.email||'Sin contacto')}</strong><button data-request="${r.id}">Abrir solicitud</button></div></article>`).join('');$('[data-requests-empty]').hidden=rows.length>0;$$('[data-request]').forEach(b=>b.onclick=()=>openRequest(b.dataset.request))}
function renderTemplates(){$('[data-templates]').innerHTML=S.templates.map(t=>`<article class="template-card"><div class="template-preview template-${esc(t.category)}"><span>LN</span></div><p class="admin-eyebrow">${esc(t.category)}</p><h3>${esc(t.name)}</h3><p>${esc(t.description||'Plantilla editable')}</p><button data-template-event="${esc(t.template_key)}">Crear evento con esta plantilla</button></article>`).join('');$$('[data-template-event]').forEach(b=>b.onclick=()=>openEvent(null,b.dataset.templateEvent))}
function renderMembers(){const em=new Map(S.events.map(e=>[e.id,e]));$('[data-members]').innerHTML=S.members.map(m=>`<article class="member-row"><div><strong>${esc(m.email)}</strong><small>${esc(em.get(m.event_id)?.name||'Evento')}</small></div><span>${roleLabel(m.role)}</span><span class="status-pill ${m.active?'status-published':'status-paused'}">${m.active?'Activo':'Pausado'}</span></article>`).join('')||'<div class="empty-state">Todavía no has asignado usuarios a eventos.</div>'}
function populateSelects(){const clients='<option value="">Sin cliente por ahora</option>'+S.clients.map(c=>`<option value="${c.id}">${esc(c.business_name)}</option>`).join('');$('#event-form [name=client_id]').innerHTML=clients;$('#event-form [name=template_key]').innerHTML=S.templates.map(t=>`<option value="${esc(t.template_key)}">${esc(t.name)}</option>`).join('');$('#member-form [name=event_id]').innerHTML=S.events.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}
function switchView(view){$$('.owner-view').forEach(p=>p.classList.toggle('active',p.dataset.panel===view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const names={inicio:['Panel general','Resumen'],eventos:['Administración','Eventos'],clientes:['Administración','Clientes'],solicitudes:['Ventas','Solicitudes'],plantillas:['Diseño','Plantillas'],usuarios:['Seguridad','Usuarios y accesos']};$('[data-section-kicker]').textContent=names[view][0];$('[data-section-title]').textContent=names[view][1];document.body.classList.remove('sidebar-open')}
function openDialog(id){$('#'+id).showModal()}
function openEvent(clientId=null,template=null){populateSelects();const f=$('#event-form');f.reset();if(clientId)f.client_id.value=clientId;if(template)f.template_key.value=template;openDialog('event-dialog')}
function openMember(){populateSelects();openDialog('member-dialog')}
async function saveClient(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.created_by=S.user.id;const {error}=await S.client.from('clients').insert(f);if(error)return alert(error.message);e.currentTarget.reset();$('#client-dialog').close();await load();switchView('clientes')}
async function saveEvent(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.created_by=S.user.id;f.qr_enabled=f.qr_enabled==='true';f.max_companions=Number(f.max_companions||3);if(!f.client_id)delete f.client_id;if(!f.event_date)delete f.event_date;const {data,error}=await S.client.from('events').insert(f).select().single();if(error)return alert(error.message);e.currentTarget.reset();$('#event-dialog').close();await load();location.href=`evento-admin.html?id=${data.id}`}
async function saveMember(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.email=f.email.trim().toLowerCase();const {error}=await S.client.from('event_members').upsert(f,{onConflict:'event_id,email'});if(error)return alert(error.message);e.currentTarget.reset();$('#member-dialog').close();await load();switchView('usuarios')}
async function saveTemplate(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.created_by=S.user.id;const {error}=await S.client.from('templates').insert(f);if(error)return alert(error.message);e.currentTarget.reset();$('#template-dialog').close();await load();switchView('plantillas')}
function openRequest(id){const r=S.requests.find(x=>x.id===id);if(!r)return;const d=$('[data-request-detail]');d.innerHTML=`<div class="dialog-title"><div><p class="admin-eyebrow">Solicitud ${esc(r.folio||'')}</p><h2>${esc(r.name)}</h2></div><button type="button" data-close-request>×</button></div><div class="request-detail"><dl><div><dt>Evento</dt><dd>${esc(r.event_type)}</dd></div><div><dt>Fecha</dt><dd>${esc(r.event_date||'Por definir')}</dd></div><div><dt>Invitados</dt><dd>${Number(r.guest_count||0)}</dd></div><div><dt>Contacto</dt><dd>${esc(r.phone||'—')}<br>${esc(r.email||'—')}</dd></div><div><dt>Estilo</dt><dd>${esc(r.style||'Por definir')}</dd></div><div><dt>Funciones</dt><dd>${esc((r.features||[]).join(', ')||'Por definir')}</dd></div></dl><p>${esc(r.details||'Sin comentarios adicionales')}</p></div><div class="dialog-actions"><button class="ghost-button" data-request-status="contacted">Marcar contactada</button><button class="primary-button" data-convert-request="${r.id}">Convertir en cliente</button></div>`;d.querySelector('[data-close-request]').onclick=()=>$('#request-dialog').close();d.querySelector('[data-request-status]').onclick=()=>updateRequest(r.id,'contacted');d.querySelector('[data-convert-request]').onclick=()=>convertRequest(r);openDialog('request-dialog')}
async function updateRequest(id,status){const {error}=await S.client.from('quote_requests').update({status}).eq('id',id);if(error)return alert(error.message);$('#request-dialog').close();await load()}
async function convertRequest(r){const {data:c,error}=await S.client.from('clients').insert({business_name:r.name,contact_name:r.name,email:r.email,phone:r.phone,notes:`Solicitud ${r.folio||''}`,created_by:S.user.id}).select().single();if(error)return alert(error.message);await S.client.from('quote_requests').update({status:'converted',converted_client_id:c.id}).eq('id',r.id);$('#request-dialog').close();await load();openEvent(c.id)}
async function logout(){await S.client.auth.signOut();location.reload()}
function set(s,v){const e=$(s);if(e)e.textContent=String(v)}function formatDate(v){return v?new Intl.DateTimeFormat('es-MX',{dateStyle:'long',timeStyle:'short'}).format(new Date(v)):'Fecha pendiente'}function statusLabel(s){return({draft:'Borrador',published:'Publicado',paused:'Pausado',finished:'Finalizado',archived:'Archivado'})[s]||s}function requestStatus(s){return({new:'Nueva',contacted:'Contactada',converted:'Convertida',archived:'Archivada'})[s]||s}function roleLabel(s){return({client_admin:'Cliente administrador',event_staff:'Personal de acceso',viewer:'Solo consulta'})[s]||s}
