import {getSupabaseClient} from './supabase.js';
const S={client:null,user:null,profile:null,events:[],clients:[],stats:{}};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.addEventListener('DOMContentLoaded',init);
async function init(){S.client=await getSupabaseClient();$('#login-form').addEventListener('submit',login);$('[data-magic]').onclick=magic;$('[data-logout]').onclick=async()=>{await S.client.auth.signOut();location.reload()};$('[data-refresh]').onclick=load;$('[data-search]').oninput=render;$('[data-status]').onchange=render;$('[data-new-client]').onclick=()=>$('#client-dialog').showModal();$('[data-new-event]').onclick=()=>openEvent();$('#client-form').addEventListener('submit',saveClient);$('#event-form').addEventListener('submit',saveEvent);const {data}=await S.client.auth.getSession();if(data.session) open(data.session.user)}
async function login(e){e.preventDefault();const f=new FormData(e.currentTarget),st=$('#login-status');st.textContent='Verificando…';const {data,error}=await S.client.auth.signInWithPassword({email:f.get('email').trim(),password:f.get('password')});if(error)return st.textContent=error.message;open(data.user)}
async function magic(){const email=$('#login-form [name=email]').value.trim();if(!email)return $('#login-status').textContent='Escribe tu correo.';const {error}=await S.client.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+'/admin'}});$('#login-status').textContent=error?error.message:'Revisa tu correo para entrar.'}
async function open(user){S.user=user;const {data:p}=await S.client.from('profiles').select('*').eq('id',user.id).maybeSingle();S.profile=p||{global_role:'client'};$('[data-login]').hidden=true;$('[data-app]').hidden=false;$('[data-role]').textContent=S.profile.global_role==='owner'?'Propietario LN Studio':S.profile.global_role==='staff'?'Equipo LN Studio':'Cliente';document.body.classList.toggle('not-owner',!['owner','staff'].includes(S.profile.global_role));await load()}
async function load(){const [{data:e,error:ee},{data:c},{data:r},{data:k}]=await Promise.all([S.client.from('events').select('*').order('created_at',{ascending:false}),S.client.from('clients').select('*').order('business_name'),S.client.from('rsvp_responses').select('event_id,attendance,party_size'),S.client.from('checkins').select('event_id,decision,entries')]);if(ee)return alert(ee.message);S.clients=c||[];const clientMap=new Map(S.clients.map(x=>[x.id,x]));S.events=(e||[]).map(x=>({...x,clients:clientMap.get(x.client_id)||null}));S.stats={r:r||[],k:k||[]};$('[data-metric-events]').textContent=S.events.filter(x=>!['archived','finished'].includes(x.status)).length;$('[data-metric-clients]').textContent=S.clients.length;$('[data-metric-confirmed]').textContent=S.stats.r.filter(x=>x.attendance==='confirmed').reduce((a,x)=>a+Number(x.party_size||0),0);$('[data-metric-checkins]').textContent=S.stats.k.filter(x=>x.decision==='approved').reduce((a,x)=>a+Number(x.entries||0),0);render()}
function render(){const q=$('[data-search]').value.toLowerCase(),status=$('[data-status]').value;const rows=S.events.filter(e=>(status==='all'||e.status===status)&&(!q||`${e.name} ${e.clients?.business_name||''}`.toLowerCase().includes(q)));$('[data-empty]').hidden=rows.length>0;$('[data-events]').innerHTML=rows.map(e=>{const conf=S.stats.r.filter(x=>x.event_id===e.id&&x.attendance==='confirmed').reduce((a,x)=>a+Number(x.party_size||0),0),check=S.stats.k.filter(x=>x.event_id===e.id&&x.decision==='approved').reduce((a,x)=>a+Number(x.entries||0),0);return `<article class="event-card"><div><span class="status-pill status-${e.status}">${esc(e.status)}</span><p class="admin-eyebrow">${esc(e.clients?.business_name||'Sin cliente')}</p><h2>${esc(e.name)}</h2><p>${e.event_date?new Intl.DateTimeFormat('es-MX',{dateStyle:'long',timeStyle:'short'}).format(new Date(e.event_date)):'Fecha pendiente'}</p></div><div class="event-card-stats"><span><b>${conf}</b> confirmados</span><span><b>${check}</b> accesos</span></div><div class="event-card-actions"><a href="evento-admin.html?id=${e.id}">Administrar</a><a href="evento.html?token=${e.private_token}" target="_blank">Abrir invitación</a><a href="scanner.html?event=${e.id}">Escáner</a></div></article>`}).join('')}
async function saveClient(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const {error}=await S.client.from('clients').insert({...f,created_by:S.user.id});if(error){alert(error.message);return}e.currentTarget.reset();$('#client-dialog').close();load()}
function openEvent(){const sel=$('#event-form [name=client_id]');sel.innerHTML=S.clients.map(c=>`<option value="${c.id}">${esc(c.business_name)}</option>`).join('');$('#event-dialog').showModal()}
async function saveEvent(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.created_by=S.user.id;f.status='draft';if(!f.event_date)delete f.event_date;const {error}=await S.client.from('events').insert(f);if(error){alert(error.message);return}e.currentTarget.reset();$('#event-dialog').close();load()}
