-- LN Studio · Control de asistencia
-- Ejecuta este archivo en Supabase > SQL Editor.

create table if not exists public.events (
  slug text primary key,
  title text not null,
  event_date timestamptz not null,
  location text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  event_slug text not null references public.events(slug) on update cascade on delete cascade,
  reference_code text not null unique,
  name text not null check (char_length(name) between 2 and 100),
  phone text not null check (char_length(phone) between 8 and 20),
  attendance text not null check (attendance in ('confirmado','no_asiste')),
  guests_count integer not null default 0 check (guests_count between 0 and 10),
  guest_names text default '',
  message text default '',
  checked_in boolean not null default false,
  checked_in_at timestamptz,
  created_at timestamptz not null default now()
);


-- Compatibilidad si la tabla ya existía antes de esta versión.
alter table public.rsvps add column if not exists reference_code text;
update public.rsvps set reference_code = 'LEGACY-' || id where reference_code is null;
alter table public.rsvps alter column reference_code set not null;
create unique index if not exists rsvps_reference_code_idx on public.rsvps(reference_code);

create index if not exists rsvps_event_slug_idx on public.rsvps(event_slug);
create index if not exists rsvps_created_at_idx on public.rsvps(created_at desc);

insert into public.events (slug,title,event_date,location,is_active)
values (
  'aniversario-fantasmas',
  'Primer aniversario Fantasmas Biker''s Shop y lanzamiento de Aliados Fantasma',
  '2026-08-29 15:00:00-06',
  'Avenida Gobernadora 656, Tolotzin I, Condominio T37, Mz. 003, Cd. Azteca, Ecatepec, Estado de México',
  true
)
on conflict (slug) do update set
  title = excluded.title,
  event_date = excluded.event_date,
  location = excluded.location,
  is_active = excluded.is_active;

alter table public.events enable row level security;
alter table public.rsvps enable row level security;

-- Cualquier invitado puede registrar una respuesta en un evento activo.
drop policy if exists "public can insert rsvps" on public.rsvps;
create policy "public can insert rsvps"
on public.rsvps for insert
to anon, authenticated
with check (
  exists (
    select 1 from public.events
    where events.slug = event_slug and events.is_active = true
  )
);

-- Solo usuarios autenticados del proyecto pueden consultar y administrar RSVP.
drop policy if exists "authenticated can read rsvps" on public.rsvps;
create policy "authenticated can read rsvps"
on public.rsvps for select
to authenticated
using (true);

drop policy if exists "authenticated can update rsvps" on public.rsvps;
create policy "authenticated can update rsvps"
on public.rsvps for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated can delete rsvps" on public.rsvps;
create policy "authenticated can delete rsvps"
on public.rsvps for delete
to authenticated
using (true);

-- Lectura pública mínima de eventos activos (útil para validaciones futuras).
drop policy if exists "public can read active events" on public.events;
create policy "public can read active events"
on public.events for select
to anon, authenticated
using (is_active = true);

-- Activa Realtime para el panel administrativo.
do $$
begin
  alter publication supabase_realtime add table public.rsvps;
exception
  when duplicate_object then null;
end $$;
