-- ============================================================
-- LN STUDIO · BASE DE DATOS PARA INVITACIONES Y RSVP
-- ============================================================
-- Ejecuta TODO este archivo en Supabase > SQL Editor > New query.
-- Después crea el usuario administrador y ejecuta supabase-admin.sql.

create table if not exists public.events (
  slug text primary key,
  title text not null,
  event_date timestamptz not null,
  location text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  event_slug text not null references public.events(slug)
    on update cascade
    on delete cascade,
  reference_code text not null unique,
  name text not null check (char_length(name) between 2 and 100),
  phone text not null check (char_length(phone) between 8 and 20),
  attendance text not null check (attendance in ('confirmado', 'no_asiste')),
  guests_count integer not null default 0 check (guests_count between 0 and 10),
  guest_names text not null default '' check (char_length(guest_names) <= 220),
  message text not null default '' check (char_length(message) <= 400),
  checked_in boolean not null default false,
  checked_in_at timestamptz,
  created_at timestamptz not null default now(),
  constraint valid_checkin_date check (
    (checked_in = false and checked_in_at is null)
    or
    (checked_in = true and checked_in_at is not null)
  )
);

-- Usuarios de Supabase Auth autorizados para administrar LN Studio.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

create index if not exists rsvps_event_slug_idx
  on public.rsvps(event_slug);

create index if not exists rsvps_created_at_idx
  on public.rsvps(created_at desc);

-- Función segura usada por las políticas RLS.
create or replace function public.is_ln_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_ln_admin() from public;
grant execute on function public.is_ln_admin() to authenticated;

-- Evento oficial.
insert into public.events (
  slug,
  title,
  event_date,
  location,
  is_active
)
values (
  'aniversario-fantasmas',
  'Primer aniversario Fantasmas Biker''s Shop y lanzamiento de Aliados Fantasma',
  '2026-08-29 15:00:00-06',
  'Avenida Gobernadora 656, Tolotzin I, Condominio T37, Mz. 003, Cd. Azteca, Ecatepec, Estado de México',
  true
)
on conflict (slug) do update set
  title = excluded.title,
  event_date = excluded.event_date,
  location = excluded.location,
  is_active = excluded.is_active;

-- RLS: seguridad obligatoria para tablas públicas.
alter table public.events enable row level security;
alter table public.rsvps enable row level security;
alter table public.admin_users enable row level security;

-- Permisos del Data API.
grant select on public.events to anon, authenticated;
grant insert on public.rsvps to anon, authenticated;
grant select, update, delete on public.rsvps to authenticated;
grant usage, select on sequence public.rsvps_id_seq to anon, authenticated;

-- EVENTOS -----------------------------------------------------
drop policy if exists "public can read active events" on public.events;
create policy "public can read active events"
on public.events
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "admins can read every event" on public.events;
create policy "admins can read every event"
on public.events
for select
to authenticated
using ((select public.is_ln_admin()));

-- RSVP PÚBLICO -------------------------------------------------
-- Un visitante solo puede crear una respuesta para un evento activo.
-- No puede marcarse como registrado en la entrada desde el formulario.
drop policy if exists "public can insert rsvps" on public.rsvps;
create policy "public can insert rsvps"
on public.rsvps
for insert
to anon, authenticated
with check (
  checked_in = false
  and checked_in_at is null
  and exists (
    select 1
    from public.events
    where events.slug = rsvps.event_slug
      and events.is_active = true
  )
);

-- PANEL ADMINISTRATIVO ----------------------------------------
drop policy if exists "admins can read rsvps" on public.rsvps;
create policy "admins can read rsvps"
on public.rsvps
for select
to authenticated
using ((select public.is_ln_admin()));

drop policy if exists "admins can update rsvps" on public.rsvps;
create policy "admins can update rsvps"
on public.rsvps
for update
to authenticated
using ((select public.is_ln_admin()))
with check ((select public.is_ln_admin()));

drop policy if exists "admins can delete rsvps" on public.rsvps;
create policy "admins can delete rsvps"
on public.rsvps
for delete
to authenticated
using ((select public.is_ln_admin()));

-- El panel recibe cambios nuevos sin recargar manualmente.
do $$
begin
  alter publication supabase_realtime add table public.rsvps;
exception
  when duplicate_object then null;
end $$;
